# Generated by Django 4.2.14 on 2024-08-01 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store1', '0003_alter_orderimages_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderimages',
            name='order_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='orderimages',
            name='product_id',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='orderimages',
            name='user_description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='orderimages',
            name='user_id',
            field=models.CharField(max_length=10),
        ),
    ]
