# Generated by Django 4.2.14 on 2024-08-02 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store1', '0004_alter_orderimages_order_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderimages',
            name='order_id',
            field=models.IntegerField(blank=True),
        ),
    ]
