# Generated by Django 4.2.14 on 2024-08-03 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store1', '0005_alter_orderimages_order_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Otp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=10)),
                ('otp', models.CharField(max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expire', models.DateField()),
            ],
        ),
    ]
