# Generated by Django 4.2.14 on 2024-08-18 03:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store1', '0009_contactus'),
    ]

    operations = [
        migrations.DeleteModel(
            name='contactus',
        ),
    ]
