# Generated by Django 4.2.14 on 2024-08-18 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store1', '0010_delete_contactus'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactVendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=20)),
                ('message', models.TextField()),
            ],
        ),
    ]
